---
id: Css_Parser
name: Css_Parser
full: CSS parser library
description: >-
  A library that provides access to the Sabberworm CSS Parser from within the
  Horde framework.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha5
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
  optional:
    ext:
      mbstring: '*'
